#!/usr/bin/env bash

export COLOR_RED=$'\033[38;5;125m'
export COLOR_GREEN=$'\033[38;5;48m'
export COLOR_YELLOW=$'\033[38;5;227m'
export COLOR_BLUE=$'\033[1;34m'
export COLOR_AQUA=$'\033[1;36m'
export COLOR_GREY=$'\033[0;90m'
export COLOR_PINK=$'\033[38;5;199m'
export COLOR_RESET=$'\033[0m'
export COLOR_LIGHT_PINK=$'\033[38;5;205m'
