#!/usr/bin/env bash

# Have less display colours
# from: https://wiki.archlinux.org/index.php/Color_output_in_console#man
export LESS_TERMCAP_mb=$'\e[1;34m'     # begin bold
export LESS_TERMCAP_md=$'\e[1;32m'     # begin blink
export LESS_TERMCAP_so=$'\e[01;44;37m' # begin reverse video
export LESS_TERMCAP_us=$'\e[1;36m'     # begin underline
export LESS_TERMCAP_me=$'\e[m'         # reset bold/blink
export LESS_TERMCAP_se=$'\e[m'         # reset reverse video
export LESS_TERMCAP_ue=$'\e[m'         # reset underline

