# frozen_string_literal: true

tap 'homebrew/bundle'
tap 'homebrew/services'
brew 'pcre'
brew 'bash'
brew 'chruby'
brew 'diffr'
brew 'git'
brew 'git-lfs'
brew 'gnupg'
brew 'jq'
brew 'pinentry-mac'
brew 'pkg-config'
brew 'shellcheck'
brew 'ruby-build'
brew 'yq'
cask '1password'
cask 'firefox'
cask 'font-inconsolata'
cask 'visual-studio-code'
cask 'ccmenu'
cask 'slack'
cask 'spotify'
