# frozen_string_literal: true

# tap 'heroku/brew'
tap 'homebrew/bundle'
tap 'homebrew/services'
# brew 'fnm'
# brew 'rust'
brew 'pcre'
brew 'bash'
brew 'chruby'
# brew 'ruby-install'
# brew 'exercism'
brew 'diffr'
brew 'git'
brew 'git-lfs'
brew 'gnupg'
brew 'jq'
brew 'pinentry-mac'
brew 'pkg-config'
# brew 'rbspy'
brew 'shellcheck'
brew 'ruby-build'
# brew 'wget'
brew 'yq'
# cask 'finicky'
# cask 'textmate'
cask '1password'
# cask 'docker'
# cask 'dropbox'
cask 'firefox'
cask 'font-inconsolata'
# cask 'google-chrome'
cask 'visual-studio-code'
cask 'ccmenu'
cask 'slack'
cask 'spotify'
