// Generated by Finicky Kickstart
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Safari",
  options: {
    hideIcon: false
  },
  handlers: [
    {
      match: finicky.matchDomains([
        "zendesk.com",
        "meet.google.com"
      ]),
      browser: "Google Chrome"
    }
  ]
}
