// Generated by Finicky Kickstart
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Safari",
  handlers: [
    {
      match: /^https?:\/\/meet\.google\.com\/.*$/,
      browser: "Google Chrome"
    },
    {
      match: /^https?:\/\/support\.marketplacer\.com\/.*$/,
      browser: "Google Chrome"
    },
    {
      match: /^https?:\/\/marketplacer\.zendesk\.com\/.*$/,
      browser: "Google Chrome"
    }
  ]
}
