#!/usr/bin/env bash

unset -f "${BASH_SOURCE##*/}"

function prompt_git_color() {
  if [[ -e .git ]]; then
    if git_status_clean; then
      if git_head_pushed; then
        echo_color AQUA
      else
        echo_color GREEN
      fi
    else
      echo_color YELLOW
    fi
  else
    echo_color RESET
  fi
}

eval "$(cat ~/.dotfiles/function_boilerplate)"

