#!/usr/bin/env bash

if [[ -f "$(brew --prefix direnv)" ]]; then
  _direnv_hook() {
    local previous_exit_status=$?;
    eval "$("$(brew --prefix direnv)" export bash)";
    return $previous_exit_status;
  };

  if ! [[ "${PROMPT_COMMAND:-}" =~ _direnv_hook ]]; then
    PROMPT_COMMAND="_direnv_hook${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
  fi
fi
