#!/usr/bin/env bash
if [[ -f "$(brew --prefix nvm)/nvm.sh" ]]; then
  export NVM_DIR="$HOME/.nvm"
  export PATH="/usr/local/opt:/usr/local/bin:/usr/local/sbin:/usr/local/lib/node:$PATH"

  source_if_exists $(brew --prefix nvm)/nvm.sh
  source_if_exists $(brew --prefix nvm)/etc/bash_completion.d/nvm
fi
export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
