#!/usr/bin/env bash

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

if [[ ! -z "$(which pyenv)" ]]; then
  eval "$(pyenv init -)"

  if [[ ! -z "$(which pyenv-virtualenv-init)" ]]; then
    eval "$(pyenv virtualenv-init -)";
  fi
fi
