#!/bin/bash
# source ~/.dotfiles/functions/bash_support.sh
# source ~/.dotfiles/functions/git_support.sh

git_system && exit 0

# cmd=$1

# only care about amend commits. pre-rebase catches rebase commits
# if [[ $cmd == "amend" ]]; then
#   git checkout HEAD@{1} &>/dev/null # treat this like a pre-rewrite thing
#   if git_rebasable HEAD^; then # is the last commit 'rewritable'
#     git checkout - &>/dev/null # then everything is fine and do nothing
#   else
#     git checkout - &>/dev/null
#     git reset --soft HEAD@{3} &>/dev/null # undo amend
#     echoerr "The following commit won't be applied:"
#     # TODO: find a way to hide the commit application feedback
#     exit 1 # I don't think this even does anything.
#   fi
# fi
