#!/usr/bin/env bash

source ~/.dotfiles/functions/bash_support.sh
source ~/.dotfiles/functions/git_support.sh

git_system && exit 0

#!/bin/sh
if  [[ -f .gitattributes ]] && grep -Fq =lfs .gitattributes; then
  command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/post-commit.\n"; exit 2; }
  git lfs post-commit "$@"
fi

git_fake_auto_stash_pop

exit 0

