#!/usr/bin/env bash

source ~/.dotfiles/functions/bash_support.sh
source ~/.dotfiles/functions/git_support.sh
source ~/.dotfiles/functions/server_support.sh
source ~/.dotfiles/functions/ruby_support.sh

git_system && exit 0

if [[ -f .gitattributes ]] && grep -Fq =lfs .gitattributes; then
  command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path.\n"; exit 2; }
  git lfs post-merge "$@"
fi

git_file_changed_after_merge "(package.json|yarn.lock)" && echodo kill_port 3308 && echodo yarn install
git_file_changed_after_merge "Gemfile(.lock)?" && echodo bundle
git_file_changed_after_merge "db/(schema.rb|structure.sql)" && rails db:migrate && echodo git stash -- db/schema.rb db/structure.sql

exit 0
