#!/bin/bash

source ~/.dotfiles/functions/bash_support.sh
source ~/.dotfiles/functions/git_support.sh

git_system && exit 0

exit_code=0

if [[ -f .eslintrc ]]; then
  js_files=$(git_modified js jsx)
  if [[ ! -z $js_files ]]; then
    git_fake_auto_stash
    echodo node_modules/.bin/eslint $js_files || exit_code=1
  fi
fi

if [[ -f .rubocop.yml ]]; then
  rb_files=$(git_modified rb jbuilder builder Gemfile)
  if [[ ! -z $rb_files ]]; then
    git_fake_auto_stash
    echodo bundle exec rubocop --parallel --force-exclusion --color $rb_files || exit_code=1
  fi
fi

exit $exit_code
