#!/usr/bin/env bash

source ~/.dotfiles/functions/bash_support.sh
source ~/.dotfiles/functions/git_support.sh

git_system && exit 0
base=$1

if git_non_release_branch $base; then
  exit 0
else
  exit 1
fi
