#!/bin/bash

source ~/.dotfiles/functions/bash_support.sh
source ~/.dotfiles/functions/git_support.sh

git_system && exit 0

exit_code=0
if [[ -f .eslintrc ]] || [[ -f .eslintrc.js ]] || [[ -f .rubocop.yml ]] || [[ .spellr.yml ]]; then
  git_fake_auto_stash
fi

if [[ -f .eslintrc ]] || [[ -f .eslintrc.js ]]; then
  js_files=$(git_modified .js .jsx .ts .tsx)
  if [[ ! -z $js_files ]]; then
    echodo node_modules/.bin/eslint --fix $js_files
    git --no-pager diff $js_files
    [[ -z "$(git diff $js_files)" ]] || exit_code=1
  fi
fi

if [[ -f .rubocop.yml ]]; then
  rb_files=$(git_modified .rb .jbuilder .builder Gemfile)
  if [[ ! -z $rb_files ]]; then
    echodo bundle exec rubocop -a --force-exclusion --color --fail-level=C --display-only-fail-level-offenses $rb_files || exit 1
    git --no-pager diff $rb_files
    [[ -z "$(git diff $rb_files)" ]] || exit_code=1
  fi
fi

if [[ -f .spellr.yml ]]; then
  if [[ ! -z "$(git_modified)" ]]; then
    CI_DOCKER=1 echodo spellr $(git_modified) || exit_code=1
  fi
fi

exit $exit_code

